# Build stage
FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o server main.go

# Runner stage
FROM alpine:3.19

WORKDIR /root/

COPY --from=builder /app/server .

EXPOSE 8080

CMD ["./server"]